/**
 * Generate world map SVG paths from Natural Earth TopoJSON data.
 * Run once: npx tsx scripts/generate-world-map.ts
 * Output: src/data/world-map-paths.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { feature } from "topojson-client";
import type { Topology, GeometryCollection } from "topojson-specification";

// Same projection used in ExploreClient.tsx
function geoToSvg(lat: number, lng: number): [number, number] {
  const x = ((lng + 180) / 360) * 1000;
  const y = ((90 - lat) / 180) * 500;
  return [x, y];
}

function coordsToPath(ring: number[][]): string {
  return ring
    .map(([lng, lat], i) => {
      const [x, y] = geoToSvg(lat, lng);
      return `${i === 0 ? "M" : "L"}${x.toFixed(1)} ${y.toFixed(1)}`;
    })
    .join(" ") + " Z";
}

function geometryToPath(geometry: GeoJSON.Geometry): string {
  const parts: string[] = [];

  if (geometry.type === "Polygon") {
    for (const ring of geometry.coordinates) {
      parts.push(coordsToPath(ring));
    }
  } else if (geometry.type === "MultiPolygon") {
    for (const polygon of geometry.coordinates) {
      for (const ring of polygon) {
        parts.push(coordsToPath(ring));
      }
    }
  }

  return parts.join(" ");
}

// Load TopoJSON from world-atlas package
const topoPath = resolve(
  dirname(new URL(import.meta.url).pathname),
  "../node_modules/world-atlas/countries-50m.json"
);
const topo: Topology = JSON.parse(readFileSync(topoPath, "utf-8"));

// Convert to GeoJSON features
const countries = feature(
  topo,
  topo.objects.countries as GeometryCollection
);

// Generate SVG paths (skip Antarctica — id "010")
const paths: string[] = [];
for (const feat of countries.features) {
  if (feat.id === "010") continue;
  const d = geometryToPath(feat.geometry);
  if (d) paths.push(d);
}

// Write output
const outDir = resolve(
  dirname(new URL(import.meta.url).pathname),
  "../src/data"
);
mkdirSync(outDir, { recursive: true });

const outPath = resolve(outDir, "world-map-paths.ts");
const content = `// Auto-generated by scripts/generate-world-map.ts — do not edit
// Source: Natural Earth 50m via world-atlas
export const worldMapPaths: string[] = ${JSON.stringify(paths, null, 2)};
`;

writeFileSync(outPath, content);
console.log(`Wrote ${paths.length} country paths to ${outPath}`);
